title: "Blog pessoal"
email: 'marcel.braghini@gmail.com'
description: "Software Developer"
baseurl: ""
url: "https://github.com/marcelbraghini/marcelbraghini.github.io"
github_username: 'marcelbraghini'
instagram_username: 'marcel.braghini'
linkedin_username: 'marcel-braghini-8b5210b6'

markdown: kramdown
plugins:
  - jekyll-paginate

paginate: 10
footer_text: '© 2020 Marcel Braghini'
admin_name: 'Marcel Braghini'
google_analytics: "UA-9999999-99"
enable_contact: true

enable_nav: true
nav_item:
  - { url: '/', text: 'Início' }
  - { url: '/sobre', text: 'Sobre' }