# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Marcel Braghini"
email: 'marcel.braghini@gmail.com'
description: "Desenvolvedor"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://github.com/marcelbraghini/marcelbraghini.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: 'marcelbraghini'
instagram_username: 'marcel.braghini'
linkedin_username: 'marcel-braghini-8b5210b6'

# Build settings
markdown: kramdown
# theme: phantom # Uncomment once published to RubyGems
plugins:
  - jekyll-paginate

### Phantom settings
paginate: 10
footer_text: '© 2018 Marcel Braghini'
admin_name: 'Marcel Braghini'
google_analytics: "UA-9999999-99" # Update with your own tracking ID
enable_contact: true

#### Phantom Navigation menu
enable_nav: true
nav_item:
  - { url: '/', text: 'Início' }
  - { url: '/sobre', text: 'Sobre' }